name: pokemate
description: A new Flutter project.
publish_to: none
version: 1.0.1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  animations: ^2.0.11
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  flutter_localized_locales: ^2.0.5
  chopper: ^8.0.3
  flutter_dotenv: ^5.2.1
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  chopper_generator: null
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/type_icons/
    - assets/images/move_classes/
    - assets/images/pokemon_icons/small/
    - assets/images/pokemon_icons/large/
    - assets/icon/
flutter_launcher_icons:
  image_path: assets/icon/icon.png
  android: true
  adaptive_icon_background: '#151218'
  adaptive_icon_foreground: assets/icon/adaptive_icon_foreground.png
  web:
    generate: true
  windows:
    generate: true
flutter_native_splash:
  color: '#151218'
  image: assets/icon/splash.png
  android_12:
    image: assets/icon/splash_android12.png
